match/urls.py
from django.urls import path, include

from . import views

app_name = 'match'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),

    # Stable marriage page
    path('stable_marriage/', views.stable_marriage, name='stable_marriage'),
    path('sm_matching/', views.sm_matching, name='sm_matching'),
    path('sm_matching_1/', views.sm_matching_1, name='sm_matching_1'),
    path('sm_matching_suitors/', views.sm_matching_suitors, name='sm_matching_suitors'),
    path('sm_matching_reviewers/', views.sm_matching_reviewers, name='sm_matching_reviewers'),
    path('sm_matching_complete/', views.sm_matching_complete, name='sm_matching_complete'),

    # Stable roommate page
    path('stable_roommate/', views.stable_roommate, name='stable_roommate'),
    path('sr_matching_roommates/', views.sr_matching_roommates, name='sr_matching_roommates'),
    path('sr_prefs/', views.sr_prefs, name='sr_prefs'),
    path('sr_matching_complete/', views.sr_matching_complete, name='sr_matching_complete'),

    # Boehmer & Heeger page
    path('boehmer_heeger/', views.boehmer_heeger, name='boehmer_heeger'),
]

whatamatch/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

match/models.py
from django.db import models

class Integer(models.Model):
    """We need numbers"""
    number = models.IntegerField()

match/forms.py
from django import forms
from django.forms import BaseFormSet

from .models import Integer


class InputForm(forms.Form):
    name = forms.CharField(max_length=20)

    def clean(self):
        cd = self.cleaned_data
        name = cd.get('name')
        if len(name) <= 1:
            raise forms.ValidationError("Name must be longer than 1 letter")



class PrefsInputForm(forms.Form):
    preferences = forms.CharField()

    def clean(self):
        cd = self.cleaned_data
        names = cd.get('preferences')
        if len(names) <= 1:
            raise forms.ValidationError("Name must be longer than 1 letter")


class IntegerInputForm(forms.ModelForm):
    class Meta:
        model = Integer
        fields = ['number']

    def clean(self):
        cd = self.cleaned_data
        number = cd.get('number')
        if number % 2 != 0:
            raise forms.ValidationError("Number must be an even number.")
        elif number <= 2:
            raise forms.ValidationError("Number cannot be <= 2.")
        elif number > 10:
            raise forms.ValidationError("As this is just a demo, please use a sample of <= 10")

match/views.py
from django.shortcuts import render, redirect
from django.forms import formset_factory
from matching.games import StableMarriage, StableRoommates
from .forms import InputForm, IntegerInputForm, PrefsInputForm
import re


def stable_marriage(request):
    """The Stable Marriage (Gale & Shapley) page"""

    # initialization for demo
    suitor_prefs = {
        'Caleb': ['Daniel', 'May', 'Ryan', 'Sadab'],
        'Mark': ['May', 'Ryan', 'Sadab', 'Daniel'],
        'Song': ['Sadab', 'Ryan', 'May', 'Daniel'],
        'Marcos': ['Daniel', 'Ryan', 'Sadab', 'May'],
    }

    reviewer_prefs = {
        'Sadab': ['Song', 'Mark', 'Caleb', 'Marcos'],
        'Ryan': ['Mark', 'Song', 'Caleb', 'Marcos'],
        'Daniel': ['Marcos', 'Mark', 'Caleb', 'Song'],
        'May': ['Mark', 'Caleb', 'Song', 'Marcos'],
    }

    # set-up dictionaries with player information's before solving
    game = StableMarriage.create_from_dictionaries(
        suitor_prefs, reviewer_prefs
    )
    results = game.solve()

    # POST data submitted; we may now process form inputs
    if request.method == "POST":
        int_form = IntegerInputForm(request.POST)
        num = int_form['number'].value()
        if int_form.is_valid():
            request.session['num'] = num
            return redirect('match:sm_matching_suitors')
    else:
        # no POST data, create a new/blank form
        int_form = IntegerInputForm()  # we need to know the number of individuals

    context = {'results': results,
               'suitor_prefs_dict': suitor_prefs,
               'reviewer_prefs_dict': reviewer_prefs,
               'int_form': int_form}
    return render(request, 'match/stable_marriage.html', context)


def sm_matching_suitors(request):
    """ Retrieve all suitors """

    num = int(request.session.get('num'))
    if not num:
        # Handle the case where 'num' is not set in the session
        return redirect('match:stable_marriage')  # Redirect to a view that sets 'num'

    SuitorFormSet = formset_factory(InputForm, min_num=int(num / 2), validate_min=True, extra=0)

    if request.method == "POST":
        # POST data submitted
        suitors = SuitorFormSet(request.POST, prefix='suitors')

        if suitors.is_valid():
            suitor_list = []
            for suitor in suitors:
                cd = suitor.cleaned_data
                name = cd.get('name')
                suitor_list.append(name)
            request.session['suitor_list'] = suitor_list
            return redirect("match:sm_matching_reviewers")  # Redirect to avoid re-submission
        else:
            pass
    else:
        # no POST data
        suitors = SuitorFormSet(prefix='suitors')

    return render(request, 'match/sm_matching_suitors.html', {
        'suitors': suitors,
    })


def sm_matching_reviewers(request):
    """ Retrieve all reviewers """
    num = int(request.session.get('num'))
    if not num:
        # Handle the case where 'num' is not set in the session
        return redirect('match:stable_marriage')  # Redirect to a view that sets 'num'

    ReviewerFormSet = formset_factory(InputForm, min_num=int(num / 2), validate_min=True, extra=0)

    if request.method == "POST":
        # POST data submitted
        reviewers = ReviewerFormSet(request.POST)

        if reviewers.is_valid():
            reviewer_list = []
            for reviewer in reviewers:
                cd = reviewer.cleaned_data
                name = cd.get('name')
                reviewer_list.append(name)

            request.session['reviewer_list'] = reviewer_list
            return redirect("match:sm_matching")  # Redirect to avoid re-submission
        else:
            pass
    else:
        # no POST data
        reviewers = ReviewerFormSet()

    return render(request, 'match/sm_matching_reviewers.html', {
        'reviewers': reviewers
    })


def sm_matching(request):
    """Retrieve the preferences for suitors"""

    suitors = request.session.get('suitor_list', [])
    reviewers = request.session.get('reviewer_list', [])

    num = len(suitors)

    SuitorPrefsFormSet = formset_factory(PrefsInputForm, min_num=num, validate_min=True, extra=0)

    if request.method == "POST":
        # Print raw POST data for debugging
        # print("POST data:", request.POST)

        formset = SuitorPrefsFormSet(request.POST, prefix='suitor_prefs')

        # Print management form errors
        # print("Management form errors:", formset.management_form.errors)

        if formset.is_valid():
            suitor_list_prefs = []

            for form in formset:
                cd = form.cleaned_data
                prefs = cd.get('preferences')
                parsed_prefs = re.split(r"[\s,]+", prefs.strip())
                suitor_list_prefs.append(parsed_prefs)

            request.session['suitor_list_prefs'] = suitor_list_prefs
            return redirect("match:sm_matching_1")  # Redirect to avoid re-submission
        else:
            # Print detailed formset errors
            #for form in formset:
            #    print(f"Form errors: {form.errors}")
            #print("Management form errors:", formset.management_form.errors)
            raise Exception("INVALID FORM DETECTED")
    else:
        formset = SuitorPrefsFormSet(prefix='suitor_prefs')

    suitors_forms = zip(suitors, formset)
    context = {'suitors_forms': suitors_forms, 'reviewers': reviewers, 'formset': formset}
    return render(request, 'match/sm_matching.html', context)


def sm_matching_1(request):
    """Retrieve the preferences for reviewers"""

    suitors = request.session.get('suitor_list', [])
    reviewers = request.session.get('reviewer_list', [])
    num = len(reviewers)

    ReviewerPrefsFormSet = formset_factory(PrefsInputForm, min_num=num, validate_min=True, extra=0)

    if request.method == "POST":
        # Print raw POST data for debugging
        #print("POST data:", request.POST)

        formset = ReviewerPrefsFormSet(request.POST, prefix='reviewer_prefs')

        # Print management form errors
        #print("Management form errors:", formset.management_form.errors)

        if formset.is_valid():
            reviewer_list_prefs = []

            for form in formset:
                cd = form.cleaned_data
                prefs = cd.get('preferences')
                parsed_prefs = re.split(r"[\s,]+", prefs.strip())
                reviewer_list_prefs.append(parsed_prefs)

            request.session['reviewer_list_prefs'] = reviewer_list_prefs
            return redirect("match:sm_matching_complete")  # Redirect to avoid re-submission
        else:
            # Print detailed formset errors
            #for form in formset:
            #    print(f"Form errors: {form.errors}")
            #print("Management form errors:", formset.management_form.errors)
            raise Exception("INVALID FORM DETECTED")
    else:
        formset = ReviewerPrefsFormSet(prefix='reviewer_prefs')

    reviewers_forms = zip(reviewers, formset)
    context = {'suitors': suitors, 'reviewers_forms': reviewers_forms, 'formset': formset}
    return render(request, 'match/sm_matching_1.html', context)



def sm_matching_complete(request):
    """Displays the results of the SM matching"""

    suitors = request.session['suitor_list']
    reviewers = request.session['reviewer_list']
    suitor_list_prefs = request.session['suitor_list_prefs']
    reviewer_list_prefs = request.session['reviewer_list_prefs']
    suitor_prefs = {}
    reviewer_prefs = {}


    index = 0
    for this_suitor_pref in suitor_list_prefs:
        suitor_prefs[suitors[index]] = this_suitor_pref
        index += 1

    index = 0
    for this_reviewer_pref in reviewer_list_prefs:
        reviewer_prefs[reviewers[index]] = this_reviewer_pref
        index += 1


    # Ensure that each player has ranked all other players
    set_of_players = set(suitor_prefs.keys())
    set_of_reviewers = set(reviewer_prefs.keys())
    for player, preferences in suitor_prefs.items():
        if set(preferences) != set_of_reviewers:
            missing_players = set_of_reviewers - set(preferences)
            suitor_prefs[player].extend(list(missing_players))

    for player, preferences in reviewer_prefs.items():
        if set(preferences) != set_of_players:
            missing_players = set_of_players - set(preferences)
            reviewer_prefs[player].extend(list(missing_players))

    # set-up dictionaries with player information's before solving
    game = StableMarriage.create_from_dictionaries(
        suitor_prefs, reviewer_prefs
    )
    results = game.solve()

    context = {
        'results': results,
        'suitor_prefs_dict': suitor_prefs,
        'reviewer_prefs_dict': reviewer_prefs,
    }
    return render(request, 'match/sm_matching_complete.html', context)


def stable_roommate(request):
    """The Stable Roommate (Robert Irving) page"""

    suitor_with_prefs = {
        'Caleb': ['Sadab', 'Ryan', 'Alex', 'Luis'],
        'May': ['Yoomin', 'Sadab', 'Ryan', 'Alex'],
        'Luis': ['Yoomin', 'Sadab', 'Ryan', 'Alex'],
        'Sadab': ['Ryan', 'Alex', 'Luis', 'Caleb'],
        'Ryan': ['Alex', 'Luis', 'Caleb', 'Amber'],
        'Alex': ['May', 'Yoomin', 'Sadab', 'Ryan'],
        'Yoomin': ['Sadab', 'Ryan', 'Alex', 'Luis'],
        'Amber': ['Ryan', 'Alex', 'Luis', 'Caleb'],
    }

    # Ensure that each player has ranked all other players
    players = set(suitor_with_prefs.keys())
    for player, preferences in suitor_with_prefs.items():
        if set(preferences) != players - {player}:
            missing_players = players - set(preferences) - {player}
            suitor_with_prefs[player].extend(list(missing_players))

    game = StableRoommates.create_from_dictionary(suitor_with_prefs)
    sr_results = game.solve()

    # POST data submitted; we may now process form inputs
    if request.method == "POST":
        int_form = IntegerInputForm(request.POST)
        num = int_form['number'].value()

match/templates/match/boehmer_heeger.html
<!DOCTYPE html>
<html lang="en">
{% extends 'what_a_match/base.html' %}
<head>
    <meta charset="UTF-8">
    <title>Contact</title>
</head>
{% block page_header %}
  <h2>Adapting Stable Matchings to Forced and Forbidden Pairs</h2>
{% endblock page_header %}

{% block content %}
<body>
<p>Boehmer & Heeger's paper introduces the problem of adapting stable matchings to forced and forbidden pairs within the
    context of classical stable matching settings, including Stable Roommates and Stable Marriage with ties. The goal is
    to find a stable matching that incorporates a given stable matching (M1), forced pairs (Q), and avoids forbidden
    pairs (P). The paper presents a polynomial-time algorithm based on the theory of rotations for adapting Stable
    Roommates matchings to forced pairs. It demonstrates that addressing forbidden pairs is NP-hard, but extends the
    polynomial-time algorithm to a fixed-parameter tractable algorithm when both forced and forbidden pairs are present.
    <br><br>
    The study also explores the impact of preferences containing ties, revealing that algorithmic results may be
    extended or that formerly tractable problems become intractable, depending on the chosen stability criterion.</p>
<h1>UNDER CONSTRUCTION.</h1>
<p>[*] Niclas Boehmer and Klaus Heeger. 2023. Adapting Stable Matchings to Forced and Forbidden Pairs. In Proceedings of the 2023 International Conference on Autonomous Agents and Multiagent Systems (AAMAS '23). International Foundation for Autonomous Agents and Multiagent Systems, Richland, SC, 985–993.<br></p>
</body>
{% endblock content %}
</html>

match/templates/match/sm_matching.html
<!DOCTYPE html>
<html lang="en">
{% extends 'what_a_match/base.html' %}

<head>
    <meta charset="UTF-8">
    <title>Stable Marriage Matching</title>
</head>
{% block page_header %}
  <h2>SM Matching</h2>
{% endblock page_header %}

{% block content %}
<body>
<br>
<h4>Initialization</h4><hr>

<div class="align">
<h5>Now enter the preferences of each suitor, <b>separated by a comma.</b> Otherwise it won't work.</h5> <i>Please note: What-A-Match will fill in missing preferences on your behalf, this is to prevent any bugs.</i>
<br>
<hr>
<h5><b><u>Suitors</u></b></h5>

<form action="{% url 'match:sm_matching' %}" method="post">
    {% csrf_token %}
    {{ formset.management_form }}
    {% for suitor, form in suitors_forms %}
        <p><b>{{ suitor }}</b>'s {{ form.preferences.label_tag }} {{ form.preferences }}</p>
    {% endfor %}
    <input type="submit" value="Submit">
</form>

<br>
<b>Here are the list of reviewers (for your reference)</b>
{% for reviewer in reviewers %}
    <p>{{ reviewer }}</p>
{% endfor %}

<br>
</div>
</body>
    <style>.align{ text-align: center; }</style>
{% endblock content %}
</html>

match/templates/match/sm_matching_1.html
<!DOCTYPE html>
<html lang="en">
{% extends 'what_a_match/base.html' %}

<head>
    <meta charset="UTF-8">
    <title>Stable Marriage Matching</title>
</head>
{% block page_header %}
  <h2>SM Matching</h2>
{% endblock page_header %}

{% block content %}
<body>
<div class="align">
<br><h4>Initialization</h4><hr>
<h5>Now enter the preferences of each reviewer, <b>separated by a comma.</b> Otherwise it won't work.</h5> <i>Please note: What-A-Match will fill in missing preferences on your behalf, this is to prevent any bugs.</i>
<hr>
<br>

<h5><b><u>Reviewers</u></b></h5>

<form action="{% url 'match:sm_matching_1' %}" method="post">
    {% csrf_token %}
    {{ formset.management_form }}
    {% for reviewer, form in reviewers_forms %}
        <p><b>{{ reviewer }}</b>'s: {{ form.preferences.label_tag }} {{ form.preferences }}</p>
    {% endfor %}
    <input type="submit" value="Submit">
</form>

<br>
<b>Here are the list of suitors (for your reference)</b>
{% for suitor in suitors %}
    <p>{{ suitor }}</p>
{% endfor %}

<br>
</div>
</body>
    <style>.align{ text-align: center; }</style>
{% endblock content %}
</html>

match/templates/match/sm_matching_complete.html
<!DOCTYPE html>
<html lang="en">
{% extends 'what_a_match/base.html' %}

<head>
    <meta charset="UTF-8">
    <title>Stable Marriage Matching</title>
</head>

{% block page_header %}
  <h2>SM Matching</h2>
{% endblock page_header %}

{% block content %}
<body>
<div class="loader"></div>
<p>Match completed successfully!</p>
<div class="loader"></div>
<hr><h4>Results</h4>
<hr>

<h5><b>Suitors</b> (this was your <i>set A</i> for the SM problem)</h5>
<table>
    {% for suitor,prefs in suitor_prefs_dict.items %}
        <tr>
            <th>{{suitor}}'s preferences: </th>
            <td>{{prefs}}</td>
        </tr>
    {% endfor %}
    </table>
<br>
<h5><b>Reviewers</b> (this was your <i>set B</i> for the SM problem)</h5>
<table>
    {% for suitor,prefs in reviewer_prefs_dict.items %}
        <tr>
            <th>{{suitor}}'s preferences:</th> <td>{{prefs}}</td>
        </tr>
    {% endfor %}
    </table>
<hr>

<h4><b>Results</b></h4>
<table class="table table-bordered">
    {% for match,partner in results.items %}
      <tr>
          <td><b>{{match}}</b> matched with <b>{{partner}}</b></td>
      </tr>
    {% empty %}
      <li class="list-group-item border-0">No existing matchings could be made.</li>
    {% endfor %}
</table>

<br><br>
<br>
<hr>
[*] Gale, D., and L. S. Shapley. “College Admissions and the Stability of Marriage.” The American Mathematical Monthly, vol. 69, no. 1, 1962, pp. 9–15. JSTOR, https://doi.org/10.2307/2312726.<br>
</body>
{% endblock content %}
</html>

match/templates/match/sm_matching_reviewers.html
<!DOCTYPE html>
<html lang="en">
{% extends 'what_a_match/base.html' %}

<head>
    <meta charset="UTF-8">
    <title>Stable Marriage Matching</title>
</head>
{% block page_header %}
  <h2>SM Matching</h2>
{% endblock page_header %}

{% block content %}
<body>

<br><h4>Initialization</h4>
<hr>
<div class ='reviewers'>
<h5>Enter the names of all reviewers to be matched</h5>
<br>
<h5><b>Reviewers</b></h5>
<form action="{% url 'match:sm_matching_reviewers' %}" method="post">
    {% csrf_token %}
        {{ reviewers.management_form }}
        {{ reviewers.as_p }}
    <input type="submit" value="Submit">
</form>
</div>
<style>.reviewers{ text-align: center; }</style>
</body>
{% endblock content %}
</html>

match/templates/match/sm_matching_suitors.html
<!DOCTYPE html>
<html lang="en">
{% extends 'what_a_match/base.html' %}

<head>
    <meta charset="UTF-8">
    <title>Stable Marriage Matching</title>
</head>
{% block page_header %}
  <h2>SM Matching</h2>
{% endblock page_header %}

{% block content %}
<body>

<br><h4>Initialization</h4><hr>
<div class ='suitors'>
<h5>Enter the names of all suitors to be matched</h5>
<br>
<h5><b>Suitors</b></h5>
<form action="{% url 'match:sm_matching_suitors' %}" method="post">
    {% csrf_token %}
        {{ suitors.management_form }}
        {{ suitors.as_p }}
    <input type="submit" value="Submit">
</form>
</div>
<style>.suitors{ text-align: center; }</style>
</body>
{% endblock content %}
</html>

match/templates/match/sr_matching.html
<!DOCTYPE html>
<html lang="en">
{% extends 'what_a_match/base.html' %}

<head>
    <meta charset="UTF-8">
    <title>Stable Marriage Matching</title>
</head>

{% block page_header %}
  <h2>SM Matching</h2>
{% endblock page_header %}

{% block content %}
<body>
<div class="loader"></div>
<p>Match completed successfully!</p>
<div class="loader"></div>
<hr><h4>Results</h4>
<hr>

<h5><b>Suitors</b> (this was your <i>set A</i> for the SM problem)</h5>
<table>
    {% for suitor,prefs in suitor_prefs_dict.items %}
        <tr>
            <th>{{suitor}}'s preferences: </th>
            <td>{{prefs}}</td>
        </tr>
    {% endfor %}
    </table>
<br>
<h5><b>Reviewers</b> (this was your <i>set B</i> for the SM problem)</h5>
<table>
    {% for suitor,prefs in reviewer_prefs_dict.items %}
        <tr>
            <th>{{suitor}}'s preferences: </th>
            <td>{{prefs}}</td>
        </tr>
    {% endfor %}
    </table>
<hr>

<h4><b>Results</b></h4>
<table class="border-bottom pb-2 mb-4 list-group-item border-0">
    {% for match,partner in results.items %}
      <tr>
          <td><b>{{match}}</b> matched with <b>{{partner}}</b></td>
      </tr>
    {% empty %}
      <li class="list-group-item border-0">No existing matchings could be made.</li>
    {% endfor %}
</table>

<br><br>
<br>
<hr>
[*] Gale, D., and L. S. Shapley. “College Admissions and the Stability of Marriage.” The American Mathematical Monthly, vol. 69, no. 1, 1962, pp. 9–15. JSTOR, https://doi.org/10.2307/2312726.<br>
</body>
{% endblock content %}
</html>

match/templates/match/sr_matching_complete.html
<!DOCTYPE html>
<html lang="en">
{% extends 'what_a_match/base.html' %}

<head>
    <meta charset="UTF-8">
    <title>Stable Roommate Matching</title>
</head>

{% block page_header %}
  <h2>SR Matching</h2>
{% endblock page_header %}

{% block content %}
<body>
<div class="loader"></div>
<p>Match completed successfully!</p>
<div class="loader"></div>
<hr><h4>Results</h4>
<hr>

<h5><b>All Suitors</b> (this was your <i>set A</i> for the SR problem)</h5>
<table>
    {% for suitor,prefs in sr_suitor_prefs_dict.items %}
        <tr>
            <th>{{suitor}}'s preferences: </th>
            <td>{{prefs}}</td>
        </tr>
    {% endfor %}
    </table>
<br>
<hr>

<h4><b>Results</b></h4>
<table class="table table-bordered">
    {% for match,partner in sr_results.items %}
      <tr>
          <td><b>{{match}}</b> matched with <b>{{partner}}</b></td>
      </tr>
    {% empty %}
      <li class="list-group-item border-0">No existing matchings could be made.</li>
    {% endfor %}
</table>

<br><br>
<br>
<hr>
[*] Gale, D., and L. S. Shapley. “College Admissions and the Stability of Marriage.” The American Mathematical Monthly, vol. 69, no. 1, 1962, pp. 9–15. JSTOR, https://doi.org/10.2307/2312726.<br>
</body>
{% endblock content %}
</html>

match/templates/match/sr_matching_roommates.html
<!DOCTYPE html>
<html lang="en">
{% extends 'what_a_match/base.html' %}

<head>
    <meta charset="UTF-8">
    <title>Stable Roommate Matching</title>
</head>
{% block page_header %}
  <h2>SR Matching</h2>
{% endblock page_header %}

{% block content %}
<body>
<br>
<h4>Initialization</h4><hr>
<div class="align">
<br>
<h5>Enter all suitors to be matched</h5>
<br>
<h5><b>Suitors</b></h5>
<form action="{% url 'match:sr_matching_roommates' %}" method="post">
    {% csrf_token %}
        {{ sr_suitors.management_form }}
        {{ sr_suitors.as_p }}
    <input type="submit" value="Submit">
</form>
<br>
<br>
</div>
</body>
    <style> .align{ text-align: center; }</style>

{% endblock content %}
</html>

match/templates/match/sr_matching_suitors.html
<!DOCTYPE html>
<html lang="en">
{% extends 'what_a_match/base.html' %}

<head>
    <meta charset="UTF-8">
    <title>Stable Roommate Matching</title>
</head>
{% block page_header %}
  <h2>SR Matching</h2>
{% endblock page_header %}

{% block content %}
<body>
<p>This page will allow the user to enter names of all roommates to be matched. </p>

<hr><h4>Initialization</h4>
<h5>Enter all suitors to be matched</h5>
<br>
<b>Suitors</b>
<form action="{% url 'match:sr_matching_suitors' %}" method="post">
    {% csrf_token %}
        {{ suitors.management_form }}
        {{ suitors.as_p }}
    <input type="submit" value="Submit">
</form>
<br>


<br>

</body>
{% endblock content %}
</html>

match/templates/match/sr_prefs.html
<!DOCTYPE html>
<html lang="en">
{% extends 'what_a_match/base.html' %}

<head>
    <meta charset="UTF-8">
    <title>Stable Marriage Matching</title>
</head>
{% block page_header %}
  <h2>SM Matching</h2>
{% endblock page_header %}

{% block content %}
<body>
<br><h4>Initialization</h4><hr>
<div class="align">
<h5>Now enter the preferences of each roommate, <b>separated by a comma.</b> Otherwise it won't work.</h5> <i>Please note: What-A-Match will fill in missing preferences on your behalf, this is to prevent any bugs.</i>
<hr>
<br>
<b>Roommates :D</b>
<form action="{% url 'match:sr_prefs' %}" method="post">
    {% csrf_token %}
    {{ formset.management_form }}

    {% for roommate, form in roommates_forms %}
        <p><b>{{ roommate }}</b>'s: {{ form.preferences.label_tag }} {{ form.preferences }}</p>
    {% endfor %}
    <input type="submit" value="Submit">
</form>

<br>
<b>Here are the list of all roommates (for your reference)</b>
{% for roomie in roommates %}
    <p>{{ roomie }}</p>
{% endfor %}

</div>
<br>
</body>
    <style>.align{ text-align: center; }</style>
{% endblock content %}
</html>

match/templates/match/stable_roommate.html
<!DOCTYPE html>
<html lang="en">
{% extends 'what_a_match/base.html' %}
<head>
    <meta charset="UTF-8">
    <title>Stable Roommates</title>
</head>
{% block page_header %}
  <h2>Stable Roommates</h2>
{% endblock page_header %}

{% block content %}
<body>
<p>
    The stable roommates problem involves a single set of even cardinality n, each member of which ranks all the others in order of preference.
    A stable matching is now a partition of this single set into n^2 pairs so that no two unmatched members both prefer each other to their
    partners under the matching. In this case, there are problem instances for which no stable matching exists. However,
    Irving's paper describes an O(n^2) algorithm that will determine, for any instance of the problem, whether a stable matching exists,
    and if so, will find that matching.
</p>
<hr>
<h4>Demo</h4>
<hr>
<h5><u><b>Set A</b></u> (only single set needed for the SR problem)</h5>
<table>
    {% for suitor,prefs in sr_suitor_prefs_dict.items %}
        <tr>
            <th>{{suitor}}</th>
            <td>{{prefs}}</td>
        </tr>
    {% endfor %}
    </table>
<hr>
{# results #}
<h5><u><b>Results</b></u></h5>
<table class="table table-bordered">
    {% for match,partner in sr_results.items %}
      <tr>
          <td><b>{{match}}</b> matched with <b>{{partner}}</b></td>
      </tr>
    {% empty %}
      <li class="list-group-item border-0">No existing matchings could be made.</li>
    {% endfor %}
</table>

<h4>Try it yourself!</h4>
<form action="{% url 'match:stable_roommate' %}" method='post'>
    {% csrf_token %}
    <p>Start by entering the total number of people being matched (from both sets):</p>
    {{ sr_int_form.as_table }}
    <input type="submit" value="Submit">
</form>
<br><br>
<br>
<hr>

<p>[*] Robert W. Irving, "An efficient algorithm for the “stable roommates” problem",
    Journal of Algorithms, Volume 6, Issue 4, 1985, Pages 577-595</p>
</body>
{% endblock content %}
</html>