match/urls.py
from django.urls import path, include

from . import views

app_name = 'match'
urlpatterns = [
    # Include default auth urls.
    path('', include('django.contrib.auth.urls')),

    # Stable marriage page
    path('stable_marriage/', views.stable_marriage, name='stable_marriage'),
    path('sm_matching/', views.sm_matching, name='sm_matching'),
    path('sm_matching_1/', views.sm_matching_1, name='sm_matching_1'),
    path('sm_matching_suitors/', views.sm_matching_suitors, name='sm_matching_suitors'),
    path('sm_matching_reviewers/', views.sm_matching_reviewers, name='sm_matching_reviewers'),
    path('sm_matching_complete/', views.sm_matching_complete, name='sm_matching_complete'),

    # Stable roommate page
    path('stable_roommate/', views.stable_roommate, name='stable_roommate'),
    path('sr_matching_roommates/', views.sr_matching_roommates, name='sr_matching_roommates'),
    path('sr_prefs/', views.sr_prefs, name='sr_prefs'),
    path('sr_matching_complete/', views.sr_matching_complete, name='sr_matching_complete'),

    # Boehmer & Heeger page
    path('boehmer_heeger/', views.boehmer_heeger, name='boehmer_heeger'),
]

what_a_match/urls.py
from django.urls import path

from . import views

app_name = 'what_a_match'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
]

whatamatch/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

what_a_match/models.py
from django.db import models
from django.contrib.auth.models import User

what_a_match/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, redirect



def index(request):
    """Public homepage for What-A-Match"""
    return render(request, 'what_a_match/index.html')

what_a_match/templates/what_a_match/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>What-A-Match</title>
  <!-- Use the Bootswatch Pulse theme -->
  <link href="https://cdn.jsdelivr.net/npm/bootswatch@5.3.3/dist/pulse/bootstrap.min.css" rel="stylesheet">
  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">

</head>
<body>
  <nav class="navbar navbar-expand-sm bg-primary navbar-dark mb-4 border justify-content-center">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'what_a_match:index' %}">What-a-Match</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
        data-bs-target="#navbarCollapse" aria-controls="navbarCollapse"
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'match:stable_marriage' %}">Stable Marriage</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'match:stable_roommate' %}">Stable Roommates</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'match:boehmer_heeger' %}">Boehmer & Heeger</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://github.com/umarhunter/what-a-match/">Repo</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <main class="container">
    <div class="pb-2 mb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>
  </main>
</body>
</html>

what_a_match/templates/what_a_match/index.html
{% extends 'what_a_match/base.html' %}

{% block page_header %}
    <body>
    <div class="p-3 mb-4 bg-light border rounded-3">
        <div class="container-fluid py-3">
            <h1 class="display-3">Stable matchings help people/systems stay "connected" 🔌</h1>
        </div>
    </div>
            <div class="p-3 mb-4 bg-light">
             <div class="container-fluid py-3">
            <p class="lead">Stable matchings, as shown by <a href="https://www.jstor.org/stable/2312726">Gale and Shapley's algorithm in 1962</a>, play a pivotal role in various
                real-world scenarios, particularly in matchmaking processes where compatibility and mutual satisfaction are paramount.
                The algorithm ensures that no two individuals have an incentive to deviate from their assigned partners, thereby
                fostering fairness and stability. This concept finds application in diverse fields such as online dating platforms,
                job placements, and even organ transplants,
                where the compatibility of pairs significantly impacts the overall system efficiency.<br><br>

                Similarly, the Stable Roommates Problem, tackled by <a href="https://www.sciencedirect.com/science/article/abs/pii/0196677485900331">Robert Irving's algorithm in 1985</a>, is of great significance in real-world scenarios where resource allocation and preferences come into play. Whether it's assigning dormitory rooms,
                office spaces, or roommate pairings, this algorithm ensures stability by preventing cycles of preferences that could lead to dissatisfaction or conflicts among individuals. By optimizing roommate assignments based on
                preferences, it contributes to harmonious living arrangements, efficient space utilization, and improved overall satisfaction. This algorithmic approach finds practical use in real estate, student housing assignments, and
                workplace logistics, where creating stable and content cohabitation or co-working environments is essential.<br><br>

                Finally, Niclas Boehmer and his colleague Klaus Heeger are attempting to build on top of these ideas. In a recent paper from 2022,
                <a href="https://doi.org/10.48550/arXiv.2204.10040">"Adapting Stable Matchings to Forced and Forbidden Pairs"</a>, Boehmer
                & Heeger introduced the idea of adapting existing stable matches to a new set of forced and forbidden pairs. The idea was to
                create new matches while trying to keep it as close to the original match. <br><br>

                To better understand how these algorithm work, you may click whichever matching method interests you to learn more.
            </p>

            <a class="btn btn-outline-primary btn-lg mt-1"
               href="{% url 'match:stable_marriage' %}">Stable Marriage &raquo;</a>
            <a class="btn btn-outline-primary btn-lg mt-1"
               href="{% url 'match:stable_roommate' %}">Stable Roommates &raquo;</a>
            <a class="btn btn-outline-primary btn-lg mt-1"
               href="{% url 'match:boehmer_heeger' %}">Boehmer & Heeger &raquo;</a>
        </div>
    </div>
    </body>
{% endblock page_header %}